---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-bootstrap-python
      ansible.builtin.include_role:
        name: ansible-bootstrap-python
    - name: Include ansible-kea-dhcp
      ansible.builtin.include_role:
        name: ansible-kea-dhcp
